import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { ImagesStoreProvider } from "@/providers/images-store-provider";
import { getData } from "./_components/ImageContainer";
import { notFound } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Take Home Demo",
  description: "Generated by your next developer",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // demonstrating zustand (global storage) 
  const data = await getData();

  if (!data) return notFound();
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ImagesStoreProvider>
          <Header />
          {children}
        </ImagesStoreProvider>
      </body>
    </html>
  );
}
